---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 1m
  path: ./<the new folder name you made in git>/flux/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: crds